# Generated by Django 4.2.16 on 2024-10-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='status_publication',
            field=models.CharField(choices=[('Non publié', 'Non publié'), ('Publié', 'Publié')], default='Non publié', max_length=20),
        ),
    ]
