# Generated by Django 4.2.16 on 2024-10-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_evenement_status_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='status_publication',
            field=models.CharField(default='Non publié', max_length=20),
        ),
    ]
