# Generated by Django 4.2.16 on 2024-10-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_evenement_status_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='titre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
