# Generated by Django 4.2.16 on 2024-11-01 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_evenement_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='status_publication',
            field=models.CharField(choices=[('Non publié', 'Non publié'), ('Publié', 'Publié')], default='Non publié', max_length=20),
        ),
        migrations.CreateModel(
            name='ArchiveEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('lieu', models.CharField(max_length=100)),
                ('date_event', models.DateTimeField()),
                ('type_event', models.CharField(choices=[('Parascolaire', 'Parascolaire'), ('Académique', 'Académique')], max_length=50)),
                ('categorie_parascolaire', models.CharField(blank=True, choices=[('Sportive', 'Sportive'), ('Culturel', 'Culturel'), ('Artistique', 'Artistique')], max_length=50, null=True)),
                ('categorie_academique', models.CharField(blank=True, choices=[('Certifications', 'Certifications'), ('Concours', 'Concours'), ('Conférences', 'Conférences')], max_length=50, null=True)),
                ('acces_public', models.BooleanField(default=True)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='archive_covers/')),
                ('evenement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='dashboard.evenement')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
